backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: assets
collections:
  - name: features
    label: Features
    folder: src/markdown/features
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: test_relations
    label: Test Relations
    folder: src/markdown/test-relations
    create: true
    fields:
      - { name: title, label: Title }
      - { name: relaod, label: test reload, widget: boolean }
      - {
          name: relatedFeatures,
          label: Relation to,
          widget: relation,
          collection: features,
          searchFields: [title],
          valueField: title,
          displayFields: [title],
          multiple: true,
        }
      - { name: body, label: Body, widget: markdown }
