backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: assets
collections:
  - name: features
    label: Features
    folder: markdown/features
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
